### ISSUE TITLE
Unable to get ADC reading as Expected

### ISSUE THREAD

**Issue by rahulbari717** [siteswapjuggler/ADS8688a#3]
pin connection are 
SCLK is IO18
RST is connected 3.3V
MOSI 23
MISO 19
CS is 32  so i have add this line 

 ADS8688 bank = ADS8688(32); // Instantiate ADS8688 with PIN 32 as CS

when I am changing channel 0 and other Channels voltages but in serial plotter, serial monitor on showing 5.12 and -5.12 V only that is also depend on some timing nothing will shows if we change voltage between 0 to 3.3V in channel 0, so but it doesn't changed. 

I am getting Output log like this

Values: -5.12 V | -5.12 V | -5.12 V | -5.12 V | -5.12 V | -5.12 V | -5.12 V | -5.12 V

**Comment by siteswapjuggler** [comment]
Can you share more information, precisely : 
- what board 
- what IDE
- what schematic
- your full testing code

With -5.12 it seem like you get default value for every channel, but I can tell you more without more information.

**Comment by rahulbari717** [comment]
I am using esp32 wroom32E board integration with ADS8688a
Ide is Arduino ide 1.8.19
for schematic we take all 8 channel with respect to ground that they are floating 
pin connection are
SCLK is IO18(ESP32)
RST is connected 3.3V
MOSI 23 (ESP32)
MISO 19 (ESP32)
CS is 32 so i have add this line

after this connection code is running without any error 
but when we try to test channel 0 or any other channel gnd or 3.3v it will show some random values but it does not showing us .
So can you suggest what can I do for this 

Thanks & Regards 
Rahul B.

**Comment by siteswapjuggler** [comment]
Hello based on the information I cannot give you any proper suggestion. I still don't know what code you tried. I still don't know what schematic are and if the ADS8688 is well implemented (what aboud avdd, dvdd, refsel, if you use the diferrential inputs).

The only think I can tell is that -5.12 is one of the standard output when the digital data is 0x0000, which can imply that your SPI communication is broken or that you do not trig the conversion properly.

Please remember that this library is not under active devellopment, and published initially as an open source pre release To be more specific right know I'll not have much time to answer question about a 6 years old hobby project. Aspecially if you do not share any details and if you ask with insistance and in an unpolite way.

Hope my answer above will give you some clues.

Have a nice day.

**Comment by rahulbari717** [comment]
Thank you so much for reply.

I truly understand your concerns and sincerely apologize for any inconvenience caused by the lack of detailed information provided initially. Your patience and understanding are greatly appreciated.

Rest assured, I will double-check all hardware connections meticulously to ensure everything is properly in place. Your assistance in this matter is invaluable, and I am grateful for your support.

Thanks & Regards 
Rahul B.
